path:
  input_data_path: "data/raw/"
  output_data_root: "data/processed/"
  interim_data_root: "data/interim/"
  models_root: "models"
  logs_root: "logs"

model:
  name: "NN"

nn:
  version: 1
  epoch: 5
  early_stopping_patience: 5

svm:
  C: 1.0
